### ISSUE TITLE
[Config] WirtgenWR250

### ISSUE THREAD

**Issue by Nonnus79** [scfmod/FS22_TerraFarmMachines#3]
Hello again,

I take a look for the new version and when i tested my WirtgenWR250 the game crash when buyed on the store.

`2024-10-04 20:59 DEBUG:  Injected machine specialization to vehicle: FS22_WirtgenWR250/WirtgenWR250.xml
2024-10-04 20:59 LOAD STUFF CALL THINGY
2024-10-04 20:59 LOAD STUFF CALL THINGY
2024-10-04 20:59 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
C:/Users/nonnu/Documents/My Games/FarmingSimulator2022/mods/FS22_0_TerraFarm/scripts/MachineWorkArea.lua:147: No referenceNode found ...
`

For what i understand in this version you can use the same file for different machines but apparently is not so linear.  In this case the mod use Paladin_highDumpBucket.xml

So after testing for the mod works need this: 

`    <machine type="ripper">
        <input modes="LOWER FLATTEN SMOOTH PAINT" />
        <workArea referenceNode="groundReferenceNode" rotation="0 90 0" width="2" />
    </machine>`

**Comment by scfmod** [comment]
Thanks again :-) I'll add this as well to the queue, and push out a new release today.
